# ใช้ Node.js version 18-alpine
FROM node:18-alpine

WORKDIR /app

# ก๊อปปี้ package.json และ yarn.lock มาก่อน
COPY package.json yarn.lock ./

# ติดตั้งแพ็กเกจด้วย yarn
RUN yarn install

# ก๊อปปี้โค้ดทั้งหมดตามเข้าไป
COPY . .

# เปิดพอร์ต 5173
EXPOSE 5173

# รันแอป
CMD ["yarn", "dev", "--host"]